---
- hosts: localhost
  connection: local
  gather_facts: false
  vars_files: 
    - vars/common.yml
    - vars/vault
  tasks:
    - name: Create VM
      azure_rm_virtualmachine:
        resource_group: "{{ my_group }}"
        name: ansibledemo1
        vm_size: Standard_B1s
        admin_username: "{{ my_user }}"
        ssh_password_enabled: false
        ssh_public_keys: 
          - path: "/home/{{ my_user }}/.ssh/authorized_keys"
            #key_data: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
            key_data: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDLsJSeCw7bC4DI6ijU0ACb4YaPH5dmXGD3ip9cGv5DQrCm01ay5iDvym2sozs2/N/7A+9vh/ATsike3QPDGK8ChSbIFjVxneMsjRTDK7s2ztj3d/NG0qaKG7Ic6JrzcB3EQjC7dQYRviW1SU8HYDNwJCy3/Kn07zqGeEErUGKaYRMh8wN6y2y14EkPU24bLZ3PRmH7JPPE6w3Gtj7Fjqaqv765dQR1Dmx+TmnQuIAHfRvM2cSs8AxZzZNkz0wT2zsRHrCMNVPzI3B19RYA0MOwG3bZUbvpgv9CWWLHMp6Uy6nH4vo0GtX/coypZjtaIF/EH/VhvGjwbj7dK6Sx7R15 mdeangelo272"
        image:
          offer: UbuntuServer
          publisher: Canonical
          sku: 18.04-LTS
          version: latest
