---
- hosts: localhost
  connection: local
  gather_facts: false
  vars_files: 
    - vars/common.yml
    - vars/vault
  tasks:
    - name: Create VM
      azure_rm_virtualmachine:
        resource_group: "{{ my_group }}"
        name: ansibleWinDemo
        vm_size: Standard_B1s
        admin_username: "{{ my_user }}"
        admin_password: "{{ my_password }}"
        image:
          offer: WindowsServer
          publisher: MicrosoftWindowsServer
          sku: 2016-Datacenter
          version: latest
